### ISSUE TITLE
Docker Image

### ISSUE THREAD

**Issue by wlargou** [ibm-messaging/jmstestp#2]
Hi,

I was wondering if there is an already configured image on DockerHub, if not is there any plan to have one. Will be really efficient for quick testing of the environment.

Thank you

**Comment by stmassey** [comment]
Hi,
Thanks for your question. Where possible we do try and make utilities available for immediate consumption. In the case of jmstestp (and cphtestp), there is a need for acceptance of the license terms of the MQ client. We do try and make the process as easy as possible (and include the relevant instructions) for users to create their own images.
Sam
